name: oliveyoung-bot

on:
  schedule:
    - cron: '0 */12 * * *'  # 하루 2번 실행
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 라이브러리 설치
        run: |
          pip install -r requirements.txt


      - name: 봇 실행
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python musinsa_test.py
